[global]
background = "#1c1b34"
foreground = "#e1e0c4"
frame_color = "#292449"
highlight = "#413aa1"

[urgency_low]
foreground = "#bdab87"

[urgency_critical]
background = "#622d2d"
foreground = "#fe7c8d"
frame_color = "#aa3c55"

# vim: ft=cfg
